package com.rikerapp.riker;

public enum SharedPreferenceKey {
    FIRST_LAUNCH_AT,
    EXPERIENCED_SPLASH_SCREEN_AT,
    OFFLINE_MODE_ENABLED_AT,
    GOOGLE_FIT_ENABLED_AT,
    GOOGLE_FIT_WORKOUTS_DISABLED_AT,
    GOOGLE_FIT_BODYWEIGHTS_DISABLED_AT,
    GOOGLE_FIT_LAST_BODY_WEIGHT_END_DATE,
    GOOGLE_FIT_LAST_WORKOUT_END_DATE,
    SUPPRESSED_WEIGHTTF_DEFAULTED_TO_BODYWEIGHT_POPUP_AT,
    ENTITY_SAVED_OR_DELETED_INDICATOR,
    AUTH_TOKEN
    ;
}
